// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuxr7UogTEYxWxMJZAycLWhhfEzaL9RaI',
    appId: '1:624780649148:web:5d25120939252fabbba6b9',
    messagingSenderId: '624780649148',
    projectId: 'myapp-af039',
    authDomain: 'myapp-af039.firebaseapp.com',
    storageBucket: 'myapp-af039.appspot.com',
    measurementId: 'G-QMRBWZ4C8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_YaAPHdGiJMfpfv4S876Er7ppxThs5lE',
    appId: '1:624780649148:android:83fb2b2848e935a5bba6b9',
    messagingSenderId: '624780649148',
    projectId: 'myapp-af039',
    storageBucket: 'myapp-af039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR28VGLqxhXZSHe-xDBKqSo1hjMyHez0Q',
    appId: '1:624780649148:ios:b4bdd0ebbd7b3dd3bba6b9',
    messagingSenderId: '624780649148',
    projectId: 'myapp-af039',
    storageBucket: 'myapp-af039.appspot.com',
    iosBundleId: 'com.example.myFinances',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR28VGLqxhXZSHe-xDBKqSo1hjMyHez0Q',
    appId: '1:624780649148:ios:c7086071e3ac0937bba6b9',
    messagingSenderId: '624780649148',
    projectId: 'myapp-af039',
    storageBucket: 'myapp-af039.appspot.com',
    iosBundleId: 'com.example.myFinances.RunnerTests',
  );
}
